### ISSUE TITLE
Dots stroke material generated

### ISSUE THREAD

**Issue by trinityss** [LJ3D/AssetLibraryTools#10]
Hi,

I downloaded this material pack (https://juliosillet.gumroad.com/l/atqte) and when I import it via the "Batch import PRB texture" function and use the "Asset Browser operations" function to add them to the asset library there is "Dots Stroke" material added > 

<img width="315" alt="blender_jrhySuOgVZ" src="https://user-images.githubusercontent.com/61430022/139539632-d69f05d4-40f9-4838-a37e-7fd59432b5f4.png">

I use the default settings. Any idea? I'm using the latest 0.2.0 version and Blender 3.0 Alpha.

Thx!

**Comment by lucianjames** [comment]
That material is generated by blender by default. You could change your default startup file so it isnt there if you wanted to. I think the dots stroke material is for the 2D animation tools in blender.
