### ISSUE TITLE
old *.fbx import | error handle

### ISSUE THREAD

**Issue by ClarkParker** [LJ3D/AssetLibraryTools#5]
I've a lot of old 6100 fbx files and when batch importing the script exits with:
_RuntimeError: Error: Version 6100 unsupported, must be 7100 or later_

An option to skip these files would be handy, or perhaps it is possible to try-except the error, but dunno if this is possible with this specific runtime error and how it would affect the performance.

THX for your hard work and sharing for free!!

**Comment by lucianjames** [comment]
Should be possible to try-except it in order to keep the importer running, if you could send me a couple of the files which work so I can test that would be very helpful

**Comment by ClarkParker** [comment]
For sure:
[oldFBX_Examples.zip](https://github.com/LJ3D/AssetLibraryTools/files/7149575/oldFBX_Examples.zip)

THX for the fast response and your effort!

**Comment by lucianjames** [comment]
Should now be fixed since commit 1887298cd03c8ca68aa9726af057691bbccc7a3f

Here is a .zip file of the updated version:
[AssetLibraryTools.zip](https://github.com/LJ3D/AssetLibraryTools/files/7149599/AssetLibraryTools.zip)

**Comment by ClarkParker** [comment]
Wow... that was fast! Works perfectly... many thanks!
