### ISSUE TITLE
Blender 3.0 Alpha Principled BSDF Values

### ISSUE THREAD

**Issue by Mainman002** [LJ3D/AssetLibraryTools#8]
In Blender 3.0 Alpha the Principled BSDF node values have changed. So I went through and changed the values to these:
* Metalness = 6
* Specularity = 7
* Roughness = 9
* Emition = 19
* Alpha = 21
* Normal = 22

**Comment by lucianjames** [comment]
Should now be fixed in commit 3cf9c9d96fb65d20493661543e1a228177522d99

Instead of updating the numbers, it now uses strings to index instead, which is much better in every way
